app/src/Entity/Customer.php
<?php
/**
 * @author hR.
 */

namespace App\Entity;

use App\Entity\Traits\BlameableEntity;
use App\Repository\CustomerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass=CustomerRepository::class)
 * @Gedmo\Loggable()
 */
class Customer
{
    use TimestampableEntity;
    use BlameableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $manager;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $interlocutor;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $locality;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $website;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $logo;

    /**
     * @ORM\ManyToMany(targetEntity=JobSector::class, inversedBy="customers")
     */
    private $sector;

    /**
     * @ORM\OneToMany(targetEntity=Deal::class, mappedBy="customer", orphanRemoval=true, cascade={"persist"})
     */
    private $deals;

    public function __construct()
    {
        $this->sector = new ArrayCollection();
        $this->deals = new ArrayCollection();
        //$this->createdAt = new \DateTime();
        //$this->updatedAt = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getManager(): ?string
    {
        return $this->manager;
    }

    public function setManager(string $manager): self
    {
        $this->manager = $manager;

        return $this;
    }

    public function getInterlocutor(): ?string
    {
        return $this->interlocutor;
    }

    public function setInterlocutor(string $interlocutor): self
    {
        $this->interlocutor = $interlocutor;

        return $this;
    }

    public function getLocality(): ?string
    {
        return $this->locality;
    }

    public function setLocality(?string $locality): self
    {
        $this->locality = $locality;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * @return Collection<int, JobSector>
     */
    public function getSector(): Collection
    {
        return $this->sector;
    }

    public function getSectorAsString(): string
    {
        $sectors = [];
        /** @var JobSector $sector */
        foreach ($this->getSector() as $sector) {
            $sectors[] = $sector->getName();
        }

        return implode(" / ", $sectors);
    }

    public function addSector(JobSector $sector): self
    {
        if (!$this->sector->contains($sector)) {
            $this->sector[] = $sector;
        }

        return $this;
    }

    public function removeSector(JobSector $sector): self
    {
        $this->sector->removeElement($sector);

        return $this;
    }

    /**
     * @return Collection<int, Deal>
     */
    public function getDeals(): Collection
    {
        return $this->deals;
    }

    public function addDeal(Deal $deal): self
    {
        if (!$this->deals->contains($deal)) {
            $this->deals[] = $deal;
            $deal->setCustomer($this);
        }

        return $this;
    }

    public function removeDeal(Deal $deal): self
    {
        if ($this->deals->removeElement($deal)) {
            // set the owning side to null (unless already changed)
            if ($deal->getCustomer() === $this) {
                $deal->setCustomer(null);
            }
        }

        return $this;
    }

    public function countDeals()
    {
        return $this->getDeals()->count();
    }
}

app/src/Form/ProfileType.php
<?php

namespace App\Form;

use App\Entity\Profile;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProfileType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('receivedAt',  DateType::class, [
                'label' => 'Candidature reçu le',
                'required' => true,
            ])
            ->add('fullName',  TextType::class, [
                'label' => 'Nom et prénom',
                'required' => true,
            ])
            ->add('email',  EmailType::class, [
                'label' => 'Email',
                'required' => true,
            ])
            ->add('phone', TextType::class, [
                'label' => 'Téléphone',
                'required' => true,
            ])
            ->add('yearsOld')
            ->add('gender')
            ->add('actuallyJobTitle', TextType::class, [
                'label' => 'Poste actuel',
                'required' => true,
            ])
            ->add('hopeJobTitle')
            ->add('yearOfExperience')
            ->add('timelineExperience')
            ->add('degree')
            ->add('locality', TextType::class, [
                'label' => 'Téléphone',
                'required' => true,
            ])
            ->add('fullAddress', TextType::class, [
                'label' => 'Téléphone',
                'required' => true,
            ])
            ->add('currentSalary')
            ->add('salaryExpectationMin')
            ->add('salaryExpectationMax')
            ->add('currentState')
            ->add('comment', TextareaType::class, [
                'label' => 'Téléphone',
                'required' => true,
            ])
            ->add('source')
            ->add('curriculumVitae')
            ->add('profilePhoto')
            ->add('sectors')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Profile::class,
        ]);
    }
}

app/src/Controller/Admin/ProfileController.php
<?php
/**
 * @author hR.
 */

namespace App\Controller\Admin;

use App\Entity\Profile;
use App\Form\ProfileType;
use App\Manager\ProfileManager;
use App\Meilisearch\ProfileMeilisearch;
use App\Repository\CustomerRepository;
use App\Repository\JobSectorRepository;
use App\Repository\ProfileRepository;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/secure/profile", name="htcintranet_admin_profile_")
 *
 * @IsGranted("ROLE_CONSULTANT")
 */
class ProfileController extends AbstractController
{
    /**
     * @Route("/search", name="search", methods={"POST"}, options={"expose"=true})
     */
    public function search(Request $request, ProfileManager $profileManager): JsonResponse
    {
        return $this->json($profileManager->handleSearchRequest($request));
    }

    /**
     * @Route("/", name="list", methods={"GET"})
     */
    public function list(CustomerRepository $customerRepository, JobSectorRepository $jobSectorRepository): Response
    {
        return $this->render('profile/list.html.twig', [
            'admin_list_profile' => true,
            'customers' => $customerRepository->findAll(),
            'sectors' => $jobSectorRepository->getAllDistinct(),
        ]);
    }

    /**
     * @Route("/received", name="received", methods={"GET"})
     */
    public function received(JobSectorRepository $jobSectorRepository): Response
    {
        return $this->render('profile/received.html.twig', [
            'admin_list_profile_received' => true,
            'is_received' => true,
            'sectors' => $jobSectorRepository->getAllDistinct(),
        ]);
    }

    /**
     * @Route("/new", name="create", methods={"GET", "POST"})
     */
    public function new(Request $request, ProfileRepository $profileRepository): Response
    {
        $profile = new Profile();
        $form = $this->createForm(ProfileType::class, $profile);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $profileRepository->add($profile, true);

            return $this->redirectToRoute('htcintranet_admin_profile_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('profile/new.html.twig', [
            'profile' => $profile,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="show", methods={"GET"})
     */
    public function show(Profile $profile): Response
    {
        return $this->render('profile/show.html.twig', [
            'profile' => $profile,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Profile $profile, ProfileRepository $profileRepository): Response
    {
        $form = $this->createForm(ProfileType::class, $profile);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $profileRepository->add($profile, true);

            return $this->redirectToRoute('htcintranet_admin_profile_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('profile/edit.html.twig', [
            'profile' => $profile,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/sheet/{id}", name="sheet", methods={"GET"}, options={"expose"=true})
     */
    public function sheet(Profile $profile): JsonResponse
    {
        return $this->json([
            'success' => true,
            'sheet' => $this->renderView('profile/profile_sheet.html.twig', [
                'profile' => $profile,
            ]),
        ]);
    }
}

app/templates/profile/_delete_form.html.twig
<form method="post" action="{{ path('app_profile_delete', {'id': profile.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ profile.id) }}">
    <button class="btn">Delete</button>
</form>

app/templates/profile/_form.html.twig
{% from 'macro/macro_custom_radio_render.html.twig' import custom_radio_render_inline %}

<div class="row">
    <div class="col-lg-12">
        <!-- Basic Card Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="row">
                    <div class="col-6 d-flex align-items-center">
                        <h5 class="m-0 font-weight-bold text-primary">
                            {{ is_new ? 'Nouveau' : 'Modifier un' }} profile
                            <span class="badge badge-primary" style="font-size: 18px;">#{{ the_id }}</span>
                        </h5>
                    </div>
                    <div class="col-6">
                        <a class="btn btn-primary float-right" href="{{ path('htcintranet_admin_profile_list') }}">
                            <i class="fa fa-backward mr-2"></i>
                            Revenir à la liste des profiles
                        </a>
                    </div>
                </div>
            </div>
            {{ form_start(form, {'attr': {'id': 'form_profile'}}) }}
            <div class="card-body">
                <div class="row">
                    {% include 'flash_message/index.html.twig' %}
                    <!--div class="col-lg-5 d-none d-lg-block bg-deal-image"-->

                    <div class="col-5 p-5">

                    </div>
                    <div class="col-7 p-5">

                        {% if not is_new and profile.cvFilename %}
                            <a href="{{ base_path_profile_file~'/'~profile.cvFilename }}" data-filename="{{ profile.cvFilename }}" id="download-profile-cv" class="btn btn-secondary">
                                <i class="fa fa-download"></i>
                                Télécharger
                            </a>
                            <a href="#" class="js-show-profile-cv-file btn btn-warning" title="Aperçu du CV"
                               data-bs-toggle="modal" data-bs-target="#modal-profile-file" style="color: darkred;">
                                <i class="fa fa-eye"></i>
                                Voir
                            </a>
                        {% endif %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-4"></div>
                    <div class="col-4"></div>
                    <div class="col-2">
                        <a class="btn btn-secondary float-right" href="{{ path('htcintranet_admin_profile_list') }}">
                            <i class="fa fa-backward mr-2"></i>
                            Liste des profiles
                        </a>
                    </div>
                    <div class="col-2">
                        <button class="btn btn-primary btn-user btn-block">
                            <i class="fa fa-save mr-2"></i>
                            {{ is_new ? 'Créer' : 'Modifier' }}
                        </button>
                    </div>
                </div>
            </div>
            {{ form_widget(form._token) }}
            {{ form_end(form, {render_rest: false}) }}
        </div>
    </div>
</div>


{% if not is_new and profile.cvFilename and is_viewable_file %}
    {% include 'profile/modal_profile_cv_view_file.html.twig' %}
{% endif %}

app/templates/profile/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Profile{% endblock %}

{% block body %}
    <h1>Edit Profile</h1>

    {{ include('profile/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_profile_index') }}">back to list</a>

    {{ include('profile/_delete_form.html.twig') }}
{% endblock %}

app/templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profile index{% endblock %}

{% block body %}
    <h1>Profile index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>ReceivedAt</th>
                <th>FullName</th>
                <th>Email</th>
                <th>Phone</th>
                <th>YearsOld</th>
                <th>Gender</th>
                <th>ActuallyJobTitle</th>
                <th>HopeJobTitle</th>
                <th>YearOfExperience</th>
                <th>TimelineExperience</th>
                <th>Degree</th>
                <th>Locality</th>
                <th>FullAddress</th>
                <th>CurrentSalary</th>
                <th>SalaryExpectationMin</th>
                <th>SalaryExpectationMax</th>
                <th>CurrentState</th>
                <th>Comment</th>
                <th>Source</th>
                <th>CurriculumVitae</th>
                <th>ProfilePhoto</th>
                <th>FullNameSlugged</th>
                <th>CreatedAt</th>
                <th>UpdatedAt</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for profile in profiles %}
            <tr>
                <td>{{ profile.id }}</td>
                <td>{{ profile.receivedAt ? profile.receivedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ profile.fullName }}</td>
                <td>{{ profile.email }}</td>
                <td>{{ profile.phone }}</td>
                <td>{{ profile.yearsOld }}</td>
                <td>{{ profile.gender }}</td>
                <td>{{ profile.actuallyJobTitle }}</td>
                <td>{{ profile.hopeJobTitle }}</td>
                <td>{{ profile.yearOfExperience }}</td>
                <td>{{ profile.timelineExperience }}</td>
                <td>{{ profile.degree }}</td>
                <td>{{ profile.locality }}</td>
                <td>{{ profile.fullAddress }}</td>
                <td>{{ profile.currentSalary }}</td>
                <td>{{ profile.salaryExpectationMin }}</td>
                <td>{{ profile.salaryExpectationMax }}</td>
                <td>{{ profile.currentState }}</td>
                <td>{{ profile.comment }}</td>
                <td>{{ profile.source }}</td>
                <td>{{ profile.curriculumVitae }}</td>
                <td>{{ profile.profilePhoto }}</td>
                <td>{{ profile.fullNameSlugged }}</td>
                <td>{{ profile.createdAt ? profile.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ profile.updatedAt ? profile.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_profile_show', {'id': profile.id}) }}">show</a>
                    <a href="{{ path('app_profile_edit', {'id': profile.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="26">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_profile_new') }}">Create new</a>
{% endblock %}

app/templates/profile/list.html.twig
{% extends 'layout.html.twig' %}

{% block title %}HTC Intranet | Profile{% endblock %}

{% block inner_content %}
    <!-- Page Heading -->

    {% include 'flash_message/index.html.twig' %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row d-flex align-items-center">
                <div class="col-8">
                    <h6 class="m-0 font-weight-bold text-primary">Base de donnée des profiles candidats</h6>
                    <span id="count-result-stat"></span>
                </div>
                <div class="col-4 d-inline-block">
                    <a class="btn btn-primary float-right" href="#">
                        <i class="fa fa-plus mr-2"></i>
                        Créer un profile
                    </a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="row d-flex align-items-center">
                <div class="col-8">
                    <div class="row d-flex align-items-center">
                        <div class="input-group input-group-sm" style="width: 30% !important;">
                            <input type="text" id="search_in_received_profile" class="form form-control"
                                   placeholder="Par nom, prénom, titre/poste, localité, tél..." aria-label="Search" aria-describedby="basic-addon2" autofocus>
                            <span class="btn btn-primary" type="button" disabled>
                                    <i class="fas fa-search fa-sm"></i>
                                </span>
                        </div>
                        <div class="input-group input-group-sm" style="width: 70% !important;">
                            <label class="input-group-text btn btn-primary" for="search_profile_xp_year">XP.</label>
                            <select class="form-select {# chosen-js #}" id="search_profile_xp_year" data-placeholder="Sélectionnez...">
                                <option selected value=""></option>
                                <option value="{{ constant('App\\Entity\\Profile::XP_YEAR_TRAINEE') }}">Stage</option>
                                <option value="{{ constant('App\\Entity\\Profile::XP_YEAR_BEGINNER') }}">Débutant</option>
                                <option value="1">+ de 1 an</option>
                                <option value="2">+ de 2 ans</option>
                                <option value="3">+ de 3 ans</option>
                                <option value="5">+ de 5 ans</option>
                                <option value="8">+ de 8 ans</option>
                                <option value="10">+ de 10 ans</option>
                                <option value="15">+ de 15 ans</option>
                                <option value="20">+ de 20 ans</option>
                            </select>

                            <label class="input-group-text btn btn-primary" for="search_profile_sent_to_customer">Client</label>
                            <select class="form-select {# chosen-js #}" id="search_profile_sent_to_customer" data-placeholder="Sélectionnez...">
                                <option selected value=""></option>
                                {% for customer in customers %}
                                    <option value="{{ customer.id }}">{{ customer.name }}</option>
                                {% endfor %}
                            </select>

                            <label class="input-group-text btn btn-primary" for="search_profile_status">Statut</label>
                            <select class="form-select" id="search_profile_status">
                                <option selected value=""></option>
                                <option value="{{ constant('App\\Entity\\Profile::RECEIVED') }}">{{ constant('App\\Entity\\Profile::RECEIVED') }}</option>
                                <option value="{{ constant('App\\Entity\\Profile::INTERVIEWED') }}">{{ constant('App\\Entity\\Profile::INTERVIEWED') }}</option>
                                <option value="{{ constant('App\\Entity\\Profile::PLACED') }}">{{ constant('App\\Entity\\Profile::PLACED') }}</option>
                                {# <option value="{{ constant('App\\Entity\\Profile::SENT') }}">{{ constant('App\\Entity\\Profile::SENT') }}</option>#}
                                <option value="{{ constant('App\\Entity\\Profile::BLACKLISTED') }}">{{ constant('App\\Entity\\Profile::BLACKLISTED') }}</option>
                            </select>

                            <label class="input-group-text btn btn-primary" for="search_profile_sector">Domaines</label>
                            <select class="form-select {# chosen-js #}" id="search_profile_sector" data-placeholder="Sélectionnez...">
                                <option selected value=""></option>
                                {% for sector in sectors %}
                                    <option value="{{ sector.name }}">{{ sector.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    <div class="input-group input-group-sm">
                        <label class="input-group-text" for="search_profile_order_by">Trier par</label>
                        <select class="form-select" id="search_profile_order_by">
                            <option selected value="{{ constant('App\\Entity\\Profile::ORDER_BY_RECEIVED_AT') }}">Reçue le</option>
                            <option value="{{ constant('App\\Entity\\Profile::ORDER_BY_XP_YEAR') }}">Nb. xp</option>
                            <option value="{{ constant('App\\Entity\\Profile::ORDER_BY_FULLNAME') }}">Nom prénoms</option>
                        </select>
                        <label class="input-group-text" for="search_profile_order_by_direction">Ordre</label>
                        <select class="form-select" id="search_profile_order_by_direction">
                            <option selected value="desc">Desc</option>
                            <option value="asc">Asc</option>
                        </select>
                        <label class="input-group-text" for="search_profile_per_page">Afficher</label>
                        <select class="form-select" id="search_profile_per_page">
                            <option value="10" selected>10</option>
                            <option value="20">20</option>
                            <option value="30">30</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="full-body-search table-responsive">
                {% include 'overlay.html.twig' %}
                <table class="table table-striped table-sm mt-2 tab-htc">
                    <thead class="bg-primary text-white">
                        <tr>
                            <th scope="col" style="width: 25%">Noms, prénoms, email</th>
                            <th scope="col" style="width: 15%">Poste actuel</th>
                            <th scope="col" style="width: 5%">Expériences</th>
                            <th scope="col" style="width: 20%">Pris en entretien pour / Envoyé à</th>
                            <th scope="col" style="width: 20%">Domaines</th>
                            <th scope="col" style="width: 5%">Adresse</th>
                            <th scope="col" style="width: 5%">Actions</th>
                        </tr>
                    </thead>
                    <tbody id="content-body-search-received">

                    </tbody>
                </table>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="pagination_search mr-3 w-auto float-right">
                        <button class="btn btn-primary mr-3 rounded-circle" id="previous_button" style="font-size: 12px;" disabled> < </button>
                        <span id="info-page" class="mr-3" style="font-size: 12px;"></span>
                        <button class="btn btn-primary rounded-circle" id="next_button" style="font-size: 12px;" disabled> > </button>
                    </div>
                </div>
            </div>

        </div>
    </div>

    {% include 'profile/modal_profile_sheet.html.twig' %}
{% endblock %}

{% block javascripts %}{{ encore_entry_script_tags('profile') }}{% endblock %}

app/templates/profile/manage.html.twig
{% extends 'layout.html.twig' %}

{% block title %}HTC Intranet | Profile candidat{% endblock %}

{% block tinymce_script %}
    <script src="{{ asset('build/js/tinymce/tinymce.min.js') }}" referrerpolicy="origin"></script>
{% endblock %}

{% block inner_content %}
    {% include 'profile/_form.html.twig' with {'is_new': is_new} %}
{% endblock %}

{% block javascripts %}{{ encore_entry_script_tags('profile') }}{% endblock %}

app/templates/profile/modal_profile_cv_view_file.html.twig
<div class="modal fade" id="modal-profile-cv-file" tabindex="-1" aria-labelledby="modalDealFileLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title font-weight-bold text-primary">Aperçu du CV</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex justify-content-center align-items-center" id="js-profile-cv-file-body">
                <iframe src="{{ base_path_profile_cv_viewerjs ~ viewable_filename }}" width='1024' height='600' allowfullscreen webkitallowfullscreen></iframe>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary js-btn-close" data-bs-dismiss="modal">Fermer</button>
                <!--button type="button" class="btn btn-primary js-btn-confirm">Confirmer</button-->
            </div>
        </div>
    </div>
</div>

app/templates/profile/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Profile{% endblock %}

{% block body %}
    <h1>Create new Profile</h1>

    {{ include('profile/_form.html.twig') }}

    <a href="{{ path('app_profile_index') }}">back to list</a>
{% endblock %}

app/templates/profile/profile_sheet.html.twig
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="d-flex justify-content-center align-items-center">
            <img class="img-profile rounded-circle ml-2 mr-3" width="120px" height="120px"
                 src="{{ customer.logo ?
                 asset('uploads/customer_logo/'~customer.logo) :
                 'https://ui-avatars.com/api/?rounded=true&background=random&name='~customer.name|replace({' ' : '+'}) }}">
        </div>
        <div class="d-flex justify-content-center mt-3">
            <h3 class="m-0 font-weight-bold">{{ customer.name }}</h3>
        </div>
    </div>
    <div class="card-body">
        <div class="row m-3">
            <div class="col-6 font-weight-bold text-dark">Gérant :</div>
            <div class="col-6">{{ customer.manager }}</div>
        </div>
        <div class="row m-3">
            <div class="col-6 font-weight-bold text-dark">Intérlocuteur(s) :</div>
            <div class="col-6">{{ customer.interlocutor }}</div>
        </div>
        <div class="row m-3">
            <div class="col-6 font-weight-bold text-dark">Téléphone de(s) intérlocuteur(s) :</div>
            <div class="col-6">{{ customer.phone }}</div>
        </div>
        <div class="row m-3">
            <div class="col-6 font-weight-bold text-dark">Adresse :</div>
            <div class="col-6">{{ customer.locality }}</div>
        </div>
        <div class="row m-3">
            <div class="col-6 font-weight-bold text-dark">Domaine :</div>
            <div class="col-6">{{ customer.sectorAsString }}</div>
        </div>
        <div class="row m-3">
            <div class="col-6 font-weight-bold text-dark">Site web :</div>
            <div class="col-6">
                {% if customer.website %}
                    <a href="{{ customer.website }}">{{ customer.website }}</a>
                {% endif %}
            </div>
        </div>
        <div class="row m-3">
            <div class="col-6 font-weight-bold text-dark">Crée le :</div>
            <div class="col-6">{{ customer.createdAt ? customer.createdAt|date('d/m/Y') : '' }}</div>
        </div>
        <div class="row m-3">
            <div class="col-6 font-weight-bold text-dark">Mise à jour le :</div>
            <div class="col-6">{{ customer.updatedAt ? customer.updatedAt|date('d/m/Y') : '' }}</div>
        </div>
        <div class="row m-3">
            <div class="col-6 font-weight-bold text-dark">Listes des contrats :</div>
            <div class="col-6">--TODO--</div>
        </div>
    </div>
</div>